spring:
  application:
    name: service-registry
server:
  port: 8761
eureka:
  client:
    registerWithEureka: true  # Enable registration with Eureka
    fetchRegistry: true       # Enable fetching registry information from Eureka

management:
  endpoints:
    web:
      exposure:
        include: "*"
