global:
  scrape_interval: 15s # How frequently to scrape targets by default
  evaluation_interval: 15s # How frequently to evaluate rules by default

scrape_configs:
  - job_name: 'gateway-service'
    static_configs:
      - targets: [ 'host.docker.internal:EMPLOYEE-SERVICE:8081' ]  # Replace with your actual host

  - job_name: 'actuator'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'localhost:9090' ]  # Replace with the actual host and port where your Spring Boot app is running
